In [2]:
import pandas as pd
# 载入语料
raw = pd.read_csv("金庸-射雕英雄传txt精校版.txt",
                  names = ['txt'], sep ='aaa', encoding ="utf-8" ,engine='python')

# 章节判断用变量预处理
def m_head(tmpstr):
    return tmpstr[:1]

def m_mid(tmpstr):
    return tmpstr.find("回 ")

raw['head'] = raw.txt.apply(m_head)
raw['mid'] = raw.txt.apply(m_mid)
raw['len'] = raw.txt.apply(len)
# 章节判断
chapnum = 0
for i in range(len(raw)):
    if raw['head'][i] == "第" and raw['mid'][i] > 0 and raw['len'][i] < 30 :
        chapnum += 1
    if chapnum >= 40 and raw['txt'][i] == "附录一：成吉思汗家族" :
        chapnum = 0
    raw.loc[i, 'chap'] = chapnum
    
# 删除临时变量
del raw['head']
del raw['mid']
del raw['len']
# 提取出三四章内容
chap3=list(raw[raw.chap == 3].txt)
chap4=list(raw[raw.chap == 4].txt)

# chap3 = raw[raw['chap'] == 3].copy()
# chap3.reset_index(drop=True, inplace=True)
# chap3['paraidx'] = chap3.index
# del chap3['chap']
# del chap3['paraidx']

# chap4 = raw[raw['chap'] == 4].copy()
# chap4.reset_index(drop=True, inplace=True)
# chap4['paraidx'] = chap4.index
# del chap4['chap']
# del chap4['paraidx']


# 对三四章内容提取关键词
import jieba
import jieba.analyse
chap3_g=[]
chap4_g=[]
for w in chap3:
    chap3_g.append(jieba.analyse.extract_tags(w,20))
for w in chap4:
    chap4_g.append(jieba.analyse.extract_tags(w,20))

#选取训练集和测试集
text_chap3=chap3_g[120:150]
train_chap3=chap3_g[10:110]
text_chap4=chap4_g[150:180]
train_chap4=chap4_g[1:101]


Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\ADMINI~1\AppData\Local\Temp\jieba.cache
Loading model cost 3.033 seconds.
Prefix dict has been built succesfully.


In [10]:
chap3_g

[['第三回', '莽莽', '黄沙'],
 ['焦木', '抬入', '客舍', '悲哭', '伤处', '圆寂', '僧众', '包扎', '伤者', '寺里'],
 ['众僧',
  '韩宝驹',
  '全金发',
  '缸内',
  '响声',
  '焦木',
  '高王经',
  '声中',
  '粗索',
  '肉团',
  '那肉团',
  '三哥',
  '怒道',
  '只道',
  '哇哇大叫',
  '巨钟',
  '口诵',
  '里面',
  '丘处机',
  '不可'],
 ['柯镇恶',
  '韩宝驹',
  '恶徒',
  '中剑',
  '韩小莹',
  '段天德',
  '解毒药',
  '丘处机',
  '服下',
  '内伤',
  '神智',
  '追杀',
  '清明',
  '双腿',
  '怀中',
  '僧人',
  '救助',
  '大怒',
  '告知',
  '受伤'],
 ['朱聪',
  '南希仁',
  '全金发',
  '张阿生',
  '受震',
  '晕过去',
  '甚重',
  '养伤',
  '内伤',
  '大碍',
  '胳臂',
  '寺里',
  '折断',
  '所受',
  '腰间',
  '胸口',
  '着实',
  '一脚',
  '当下',
  '一时'],
 ['云栖寺', '监寺', '焦木禅师', '法华寺', '枯木', '禅师', '后事', '报信', '临安', '去向', '料理'],
 ['丘处机',
  '数日',
  '各人',
  '韩小莹',
  '所中',
  '朱聪',
  '痊可',
  '这日',
  '八人',
  '僧房',
  '误打',
  '焦木禅师',
  '根柢',
  '医道',
  '误杀',
  '奸人',
  '调治',
  '拨弄',
  '内伤',
  '消解'],
 ['无名之辈',
  '韩小莹',
  '丘道长',
  '示下',
  '走江湖',
  '道长',
  '皆知',
  '耻笑',
  '糊里糊涂',
  '善后',
  '英明',
  '能干',
  '江湖',
  '好汉',
  '一会',
  '流传',
  '天下',
  '手里',
  '兄弟',
  '出去'],
 ['焦木',
 

In [7]:
chap3

['第三回 黄沙莽莽',
 '寺里僧众见焦木圆寂，尽皆悲哭。有的便为伤者包扎伤处，抬入客舍。',
 '忽听得巨钟下的铜缸内当当当响声不绝，不知里面是何怪物，众僧面面相觑，手足无措，齐声口诵《高王经》，不料“救苦救难”、“阿弥陀佛”声中，缸内响声不停，最后终于大了胆子，十多个和尚合力用粗索吊起大钟，刚将铜缸掀起少许，里面滚出来一个巨大肉团。众僧大惊，四散逃开。只见那肉团站立在地，呼呼喘气，却是韩宝驹。他给罩在铜缸之中，不知后半段的战局，眼见焦木圆寂，义兄弟个个重伤，急得哇哇大叫。提起金龙鞭便欲向丘处机头顶击落。全金发叫道：“三哥，不可！”韩宝驹怒道：“为什么？”全金发腰间剧痛，只道：“千……千万不可。”',
 '柯镇恶双腿中剑，受伤不轻，神智却仍清明，从怀中摸出解毒药来，命僧人分别去给丘处机及韩小莹服下，一面将经过告知韩宝驹。韩宝驹大怒，转身奔出，要去追杀段天德。柯镇恶喝住，说道：“那恶徒慢慢再找不迟，你快救助受了内伤的众兄弟。”',
 '朱聪与南希仁所受内伤甚重。全金发腰间所受的这一脚也着实不轻。张阿生胳臂折断，胸口受震，一时痛晕过去，醒转之后，却无大碍。当下众人在寺里养伤。',
 '法华寺监寺派人到临安云栖寺去向枯木禅师报信，并为焦木禅师料理后事。',
 '过了数日，丘处机与韩小莹身上所中的毒都消解了。丘处机精通医道，开了药方给朱聪等人调治，又分别给各人推拿按摩。幸得各人根柢均厚，内伤外伤逐渐痊可，又过数日，已能坐起。这日八人聚集在一间僧房之中，想起受了奸人从中拨弄，这许多江湖上的大行家竟至误打误杀，个个重伤，还赔了焦木禅师一条性命，都黯然不语。',
 '过了一会，韩小莹首先说道：“丘道长能干英明，天下皆知，我们七兄弟也不是初走江湖之人，这次大家竟糊里糊涂地栽在这无名之辈手里，流传出去，叫江湖上好汉耻笑。这事如何善后，还得请道长示下。”',
 '丘处机这几日也是深责自己激于义愤，太过鲁莽，如不是这般性急，只消平心静气地与焦木交涉，必可弄个水落石出，便对柯镇恶道：“柯大哥，你说怎么办？”',
 '柯镇恶脾气本就怪僻，瞎了双眼之后更加乖戾，这次七兄弟被丘处机一人打倒，实是生平罕遇的奇耻大辱，再加腿上剑创兀自疼痛难当，气恼愈甚，冷笑道：“丘道长仗剑横行天下，怎把别人瞧在眼里？这事又何必再问我们兄弟？”',
 '丘处机一楞，知他气愤未消，站起身来向七人团团行了一礼，说道：

In [209]:
# import pandas as pd
# chap4_a=pd.DataFrame({'chap_g':chap4_g,'chap':4})
# chap3_a=pd.DataFrame({'chap_g':chap3_g,'chap':3})
# chap_a=pd.concat([chap4_a,chap3_a])
# from sklearn.model_selection import train_test_split
# train_chap3, test_chap3, train_chap4, text_chap4 = train_test_split(chap_a['chap_g'].values,
#                                                                     chap_a['chap'].values, 
#                                                                     test_size = 0.3, 
#                                                                     random_state = 111)

In [210]:
# # 进行训练集计算
# #求P(A|Y)=P(Y|A)*P(A)/P(Y)

# # 求PY,P(Y)
# PY={}
# PY['train_chap3']=len(train_chap3)/(len(train_chap3)+len(train_chap4))
# PY['train_chap4']=len(train_chap4)/(len(train_chap3)+len(train_chap4))

In [3]:
# 求PYA3,PYA4
#第三,四章关键词词频统计
a3=[]
for i in range(len(train_chap3)):    
    for j in train_chap3[i]:
        a3.append(j)
a4=[]
for i in range(len(train_chap4)):    
    for j in train_chap4[i]:
        a4.append(j)
b3={}
for i in a3:
    if i in b3:
        b3[i] += 1
    else:
        b3[i] = 1
b4={}
for i in a4:
    if i in b4:
        b4[i] += 1
    else:
        b4[i] = 1
c3=list(set(b3))
c4=list(set(b4))
PYA3={}
for i in c3:
    if i in b3:
        PYA3[i]=b3[i]/len(a3)
PYA4={}
for i in c4:
    if i in b4:
        PYA4[i]=b4[i]/len(a4)

In [4]:
# 对第三章训练集判断
PP3=[]
for j in range(30):
    P3 = {}
    for i in text_chap3[j]:
        if i in PYA3:
            P3[i]=PYA3[i]
        else:
            P3[i]=0.001
    PP3.append(P3)

Pl3=[]
for j in range(30):
    m=1
    for i in PP3[j]:
        m=m*PP3[j][i]
    Pl3.append(m)

PP4=[]
for j in range(30):
    P4 = {}
    for i in text_chap3[j]:
        if i in PYA4:
            P4[i]=PYA4[i]
        else:
            P4[i]=0.001
    PP4.append(P4)

Pl4=[]
for j in range(30):
    m=1
    for i in PP4[j]:
        m=m*PP4[j][i]
    Pl4.append(m)

import numpy as np
a=np.array(Pl3)
b=np.array(Pl4)
e=a>b
e

array([False, False, False, False, False,  True, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False])

In [5]:
# 对第四章训练集判断
BB3=[]
for j in range(30):
    B3 = {}
    for i in text_chap4[j]:
        if i in PYA3:
            B3[i]=PYA3[i]
        else:
            B3[i]=0.01
    BB3.append(B3)

Bl3=[]
for j in range(30):
    m=1
    for i in BB3[j]:
        m=m*BB3[j][i]
    Bl3.append(m)

BB4=[]
for j in range(30):
    B4 = {}
    for i in text_chap4[j]:
        if i in PYA4:
            B4[i]=PYA4[i]
        else:
            B4[i]=0.01
    BB4.append(B4)

Bl4=[]
for j in range(30):
    m=1
    for i in BB4[j]:
        m=m*BB4[j][i]
    Bl4.append(m)

import numpy as np
aa=np.array(Bl3)
ba=np.array(Bl4)
ea=aa>ba
ea

array([ True,  True, False, False,  True, False, False, False, False,
       False, False, False, False,  True, False, False,  True, False,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True, False,  True])

In [238]:
c = np.vstack((e,ea))
c

array([[False, False,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True, False,  True,  True,
         True,  True,  True,  True, False,  True,  True, False,  True,
        False,  True, False],
       [ True,  True, False,  True,  True,  True,  True,  True,  True,
         True, False,  True, False,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True]])

In [243]:
d=['True,'*60]
baa=np.array(d)
d

['True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,']

In [ ]:
# pred=[0]*len(tp4)
# for i in range(len(tp4)):
#     if tp3[i]>tp4[i]:
#         pred[i]=3
#     else:
#         pred[i]=4

In [241]:
from sklearn.metrics import classification_report
target_names = ['class 3', 'class 4',]
print(classification_report(d, c, target_names=target_names))

ValueError: Found input variables with inconsistent numbers of samples: [1, 2]

In [175]:
text_chap4

[['凉嗖嗖',
  '朱聪',
  '但觉',
  '犹似',
  '大青纸',
  '心增',
  '轻雷',
  '窒滞',
  '惊怖',
  '云遮',
  '浓墨',
  '斜眼',
  '脱出',
  '电光',
  '黑云',
  '缠住',
  '背心',
  '郁闷',
  '闪烁',
  '冷汗'],
 ['梅超风', '柯镇恶', '石坑', '打坐', '藏身', '弯腰', '石板', '尸首', '片刻', '起身', '之前'],
 ['六怪', '兵刃', '跃出', '紧握', '石板', '个个', '江南', '立即'],
 ['梅超风',
  '上显',
  '长啸',
  '树梢',
  '一响',
  '陡然',
  '树叶',
  '人头',
  '风声',
  '月光',
  '树上',
  '影子',
  '猛然',
  '微微',
  '回头',
  '背后',
  '似乎',
  '一声',
  '正在',
  '出来'],
 ['韩宝驹',
  '梅超风',
  '心疾',
  '扑下',
  '左掌',
  '树巅',
  '下跃',
  '微一长',
  '竟立',
  '上击',
  '反带',
  '出劲',
  '回夺',
  '身随',
  '已如',
  '风行电掣',
  '掌未到',
  '风先',
  '撤鞭',
  '翻落'],
 ['袖箭',
  '韩宝驹',
  '只感',
  '南希仁',
  '全金发',
  '透骨',
  '凉气',
  '往前',
  '竭力',
  '双双',
  '一股',
  '敌人',
  '同时'],
 ['梅超风',
  '韩宝驹',
  '右掌',
  '飘风',
  '双爪',
  '连弹',
  '弹落',
  '左足点',
  '纵出',
  '正落',
  '这铁',
  '尸动',
  '只感',
  '他大惊',
  '斩落',
  '铁锥',
  '敌人',
  '十指',
  '借势',
  '临危'],
 ['足踝',
  '梅超风',
  '提脚往',
  '首一条',
  '猛往',
  '南希仁',
  '樵子',
  '黑黝黝',
  '扁担',
  '臀部',
  '忽地',
  '南山',
  '正是'],
 ['

In [176]:
# # 求PA
# PA3 = {}
# PA4 = {}
# for i in b3:
#     PA3[i]=b3[i]/len(a3+a4)
# for i in b4:
#     PA4[i]=b4[i]/len(a3+a4)

# PA3

# text_chap=text_chap3+text_chap4


In [177]:
# test=[]
# ture=[]
# # 测试集
# d3={}
# for i in text_chap:
#     for j in i:
#         if j not in PA3.keys():
#             continue
#         d3[j]=PYA3[j]*PA3[j]/PY['train_chap3']
  

In [178]:
# test=[]
# ture=[4]*102
# for i in range(102):
#     if i<51:
#         ture[i]=3

In [179]:
# for i in d3:
#     if j not in d4.keys():
#         continue
#     if i<j:
#         test.append('3')
#     else:
#         test.append("4") 